version: '3'

services:
  ecs-ssm-sd-frontend:
    build: ./frontend/
    image: ecs-ssm-sd-frontend
    container_name: ecs-ssm-sd-frontend
    ports:
      - "80:80"
    environment:
      - SSM_AGENT_CODE
      - SSM_AGENT_ID
      - AWS_DEFAULT_REGION
      - BACKEND_HOST_URL

  ecs-ssm-sd-backend:
    build: ./backend/
    image: ecs-ssm-sd-backend
    container_name: ecs-ssm-sd-backend
    ports:
      - "8000:8000"
    environment:
      - SSM_AGENT_CODE
      - SSM_AGENT_ID
      - AWS_DEFAULT_REGION
